# workflow name
name: Custom workflow

# it will be execute on push commit in
on:
  push:
    # this is an array. can includes a few branches
    branches:
      - "development"

#tasks
jobs:
  custom_workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: message
        run: echo "This is a custom workflow "

      # I will use other action ready - made
      # this will do a checktout
      # - uses: actions/checkout@v3
      #   with:
      #    fetch-depth: 0
      # this intalles node
      # includes actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test

      # intall the dependencies
      - name: Install dependencies
        #run: npm i --no-audit --no-fund --no-optional
        run: npm ci

      # lint code
      - name: Lint
        run: npm run eslint

      # launch unit tests
      - name: Test
        run: npm run test

      # lounch e2e test
      # - name: E2E
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-test
      #     wait-on: http://localhost:5000

      # create a build
      - name: Build
        run: npm run build
